/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import SQLite.DatabaseManager;


public class UserData extends javax.swing.JFrame {

	
	
	private int rowID;
	
    public UserData(int rowID) {
    	db.connectToDatabase();
    	this.rowID = rowID;
        initComponents();
        db.closeConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	

    	
    	this.setTitle("Macro Tracker");
        jLabel4 = new javax.swing.JLabel();
        fatsProgressBar = new javax.swing.JProgressBar();
        fatsProgressBar.setValue((db.fatsAte(rowID)*100)/db.fatsGoal(rowID));

        fatsSelectButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        protienProgressBar = new javax.swing.JProgressBar();
        protienProgressBar.setValue((db.proteinAte(rowID)*100)/db.proteinGoal(rowID));

        carbsProgressBar = new javax.swing.JProgressBar();
        carbsProgressBar.setValue((db.carbsAte(rowID)*100)/db.carbsGoal(rowID));

        carbsSelectButton = new javax.swing.JButton();
        protienSelectButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CalorieProgressBar = new javax.swing.JProgressBar();
        CalorieProgressBar.setValue((db.calorieAte(rowID)*100)/db.calorieGoal(rowID));

        CalorieSelectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setMaximumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Fats");

        fatsSelectButton.setText("Select");
        fatsSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatsSelectButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Carbs");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Protien");

        carbsSelectButton.setText("Select");
        carbsSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carbsSelectButtonActionPerformed(evt);
            }
        });

        protienSelectButton.setText("Select");
        protienSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protienSelectButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Calorie");

        CalorieSelectButton.setText("Select");
        CalorieSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalorieSelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(protienProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carbsProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fatsProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CalorieProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fatsSelectButton)
                    .addComponent(carbsSelectButton)
                    .addComponent(protienSelectButton)
                    .addComponent(CalorieSelectButton))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fatsProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fatsSelectButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carbsSelectButton)
                        .addComponent(carbsProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(protienProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(protienSelectButton))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalorieProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalorieSelectButton))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        JButton profileButton = new JButton("Info");
        profileButton.setBackground(new  Color(128, 128, 128)); 
        profileButton.setBounds(350, 20, 89, 23);
        profileButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                userProfileActionPerformed(e);
            }
        });
        this.add(profileButton);
        
        JButton optionButton = new JButton("Option");
		optionButton.setBackground(new Color(128, 128, 128));
		optionButton.setBounds(305, 20, 89, 23);
		optionButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				optionButtonActionPerformed(e);
			}
		});
		this.add(optionButton);
		
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void optionButtonActionPerformed(ActionEvent e) {
		Option option = new Option(rowID);
		option.setVisible(true);
		this.dispose();
	}

    public void userProfileActionPerformed(ActionEvent e) {
        UserProfile userProfile = new UserProfile(rowID);
        userProfile.setVisible(true);
        this.dispose();
    }
    
    
    private void fatsSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	this.dispose();
    	new UpdateValue(rowID, "Fat_Ate").setVisible(true);
    }
    
    

    private void carbsSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	this.dispose();
    	new UpdateValue(rowID, "Carbs_Ate").setVisible(true);
    }

    private void protienSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	this.dispose();
		new UpdateValue(rowID, "Protein_Ate").setVisible(true);
    	
    }

    private void CalorieSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	this.dispose();
    	new UpdateValue(rowID, "Calorie_Ate").setVisible(true);
    	
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar CalorieProgressBar;
    private javax.swing.JButton CalorieSelectButton;
    private javax.swing.JProgressBar carbsProgressBar;
    private javax.swing.JButton carbsSelectButton;
    private javax.swing.JProgressBar fatsProgressBar;
    private javax.swing.JButton fatsSelectButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar protienProgressBar;
    private javax.swing.JButton protienSelectButton;
    private DatabaseManager db = new DatabaseManager();

    // End of variables declaration//GEN-END:variables
}
